version: "2.4"
services:
  weston:
    image: torizon/weston-vivante:2
    # EULA required to run imx8 vivante graphic drivers
    # Pre-accept as we ask the user accept the EULA already.
    environment:
      - ACCEPT_FSL_EULA=1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    command: --developer weston-launch --tty=/dev/tty7 --user=torizon -- --shell=kiosk-shell.so
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
      - type: bind
        source: /home/torizon/
        target: /etc/xdg/weston-dev/
      - type: bind
        source: /etc/xdg/weston/
        target: /etc/xdg/weston/
    cap_add:
      - CAP_SYS_TTY_CONFIG
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - 'c 4:0 rmw'
      # ... for tty7
      - 'c 4:7 rmw'
      # ... for /dev/input devices
      - 'c 13:* rmw'
      - 'c 199:* rmw'
      # ... for /dev/dri devices
      - 'c 226:* rmw'

  cog:
    depends_on:
    - weston
    device_cgroup_rules:
    - c 199:* rmw
    image: jrvtoradex/cog:2
    volumes:
    - /tmp:/tmp:rw
    - /var/run/dbus:/var/run/dbus
    - /dev/galcore:/dev/galcore
    - /etc/banners:/etc/banners
    command: file:///etc/banners/doom_banner.png
  doom:
    depends_on:
    - weston
    restart: on-failure
    environment:
    - ALSA_CARD=audiohdmi
    devices:
    - /dev/snd:/dev/snd
    - /dev/input/js0:/dev/input/js0
    device_cgroup_rules:
    - 'c 199:* rmw'
    - 'c 226:* rmw'
    - 'c 13:* rmw'
    image: jrvtoradex/doom-verdin-imx8m:1
    volumes:
    - /dev:/dev
    - /tmp:/tmp:rw
    - /etc/doom-config:/home/torizon/.local/share/chocolate-doom
  gpios:
    image: rudhi94/gpiod:1
    devices:
    - "/dev/gpiochip0:/dev/gpiochip0"
    volumes:
    - /etc/sota/conf.d/99-offline-updates.toml:/etc/sota/conf.d/99-offline-updates.toml
